# Generated by Django 4.1.5 on 2023-01-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModbusDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Boiler',
            fields=[
                ('modbusdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tbapp.modbusdevice')),
                ('temperature', models.FloatField()),
                ('pressure', models.FloatField()),
                ('gas', models.FloatField()),
                ('on_off', models.BooleanField()),
            ],
            bases=('tbapp.modbusdevice',),
        ),
    ]
